# Generated by Django 4.0 on 2022-01-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0009_alter_attention_id_alter_game_id_alter_gamemod_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orientation',
            name='memoryTime',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
