# Generated by Django 4.0.1 on 2022-01-25 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0011_sort_term_memory_memorytime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-add_time'],
            },
        ),
    ]
