# Generated by Django 4.0.1 on 2022-03-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0012_songlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='songlist',
            name='song_name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
