# Generated by Django 4.0.1 on 2022-04-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0015_nostalgiagame_round_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nostalgiagame_round',
            name='Correct_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nostalgiagame_round',
            name='Fail_people',
            field=models.IntegerField(default=0),
        ),
    ]
