# Generated by Django 4.0.1 on 2022-04-06 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0016_alter_nostalgiagame_round_correct_people_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NostalgiaGame_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='nostalgiagame_player',
            old_name='Connect_session',
            new_name='nostalgiaGame_round',
        ),
        migrations.RemoveField(
            model_name='nostalgiagame_round',
            name='Date',
        ),
        migrations.AddField(
            model_name='nostalgiagame_round',
            name='nostalgiaGame_time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='robot.nostalgiagame_time'),
            preserve_default=False,
        ),
    ]
