# Generated by Django 4.0.1 on 2022-04-07 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0018_nostalgiagame_round_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nostalgiagame_round',
            options={'ordering': ['-add_time']},
        ),
        migrations.AddField(
            model_name='nostalgiagame_round',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='nostalgiagame_round',
            name='Number',
            field=models.IntegerField(default=1),
        ),
    ]
