# Generated by Django 4.0.1 on 2022-04-07 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0019_alter_nostalgiagame_round_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nostalgiagame_player',
            name='mod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='robot.gamemod'),
            preserve_default=False,
        ),
    ]
