# Generated by Django 4.0.1 on 2022-04-13 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0021_remove_nostalgiagame_round_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nostalgiagame_player',
            options={'ordering': ['-add_time']},
        ),
        migrations.AddField(
            model_name='nostalgiagame_player',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
